# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
on: [ push ]

jobs:
  build:
    name: Test
    # The type of the runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.17.0 ]

    # Steps represent a sequence o tasks that will be executed as part of the job
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are started in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Node Modules
        run: npm install

      - name: Lint Test
        run: npm run lint

      - name: Build
        run: npm run build
